# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ce61f6c3ecce8e91288f5f9941b087192291d5f2457e07d9d2f3000b69a9d7c9861d5912d54f061c22cdf7abdc261f24c5aca5375188594ead82c622b15f59d

test:
  secret_key_base: da9d5582f456f99f1b5f7abec940f146ec7aa2e4beeb064221eca0fd3237048ee4637c1489f1c9eb53573232e815d93b1980c0b9bd74c98b05dc4e818eb3a602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
